<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>ModularApp.Sdk</PackageId>
    <Description>ModularApp SDK - module contracts and core service interfaces</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0-preview.1.25080.5" />
    <PackageReference Include="Semver" Version="3.0.0" />
  </ItemGroup>
</Project>
